#!/bin/bash
# Bash script to install the Multiphase LBM for Porous Media dependencies
cd src && unzip palabos-v2.zip
cd 2-phase_LBM
make
# TODO:
#1) Erase everything that is not needed (ie examples)
#2) Make the singlephase .cpp files
