#!/bin/bash 
#SBATCH -J tubes_test          # job name 
#SBATCH -o tubes_test/myMPI.o%j        # output and error file name (%j expands to jobID)
#SBATCH -N 2                # number of nodes requested 
#SBATCH -n 10               # total number of mpi tasks requested 
#SBATCH -p normal      # queue (partition) -- normal, development, etc. 
#SBATCH -t 12:00:00         # run time (hh:mm:ss) - 1.5 hours 

#Slurm email notifications are now working on Lonestar 5 
#SBATCH --mail-user=abihani@utexas.edu 
#SBATCH --mail-type=end     # email me when the job finishes 
# run the executable named a.out 
ibrun ./ShanChen_v4_new1 input_sc_tubes1.xml